//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Photo_Video_Studio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MainSlider
    {
        public int Id { get; set; }
        public string RotateHeader { get; set; }
        public string MainTitle { get; set; }
        public string Subtitle { get; set; }
        public string Image { get; set; }
    }
}
