//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Photo_Video_Studio.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PhotoStudioEntities4 : DbContext
    {
        public PhotoStudioEntities4()
            : base("name=PhotoStudioEntities4")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<About> Abouts { get; set; }
        public virtual DbSet<AboutHeader> AboutHeaders { get; set; }
        public virtual DbSet<BlogComment> BlogComments { get; set; }
        public virtual DbSet<BlogHeader> BlogHeaders { get; set; }
        public virtual DbSet<Blog> Blogs { get; set; }
        public virtual DbSet<BlogTag> BlogTags { get; set; }
        public virtual DbSet<BlogToTag> BlogToTags { get; set; }
        public virtual DbSet<ClientSlider> ClientSliders { get; set; }
        public virtual DbSet<Contact> Contacts { get; set; }
        public virtual DbSet<ContactHeader> ContactHeaders { get; set; }
        public virtual DbSet<ErrorHeader> ErrorHeaders { get; set; }
        public virtual DbSet<Fact> Facts { get; set; }
        public virtual DbSet<Gallery> Galleries { get; set; }
        public virtual DbSet<LoginHeader> LoginHeaders { get; set; }
        public virtual DbSet<MainSlider> MainSliders { get; set; }
        public virtual DbSet<News> News { get; set; }
        public virtual DbSet<NewsComment> NewsComments { get; set; }
        public virtual DbSet<NewsHeader> NewsHeaders { get; set; }
        public virtual DbSet<NewsSingleHeader> NewsSingleHeaders { get; set; }
        public virtual DbSet<NewsTag> NewsTags { get; set; }
        public virtual DbSet<NewsToTag> NewsToTags { get; set; }
        public virtual DbSet<OrderType> OrderTypes { get; set; }
        public virtual DbSet<Partner> Partners { get; set; }
        public virtual DbSet<RegisterHeader> RegisterHeaders { get; set; }
        public virtual DbSet<ServiceHeader> ServiceHeaders { get; set; }
        public virtual DbSet<Staff> Staffs { get; set; }
        public virtual DbSet<StaffOrder> StaffOrders { get; set; }
        public virtual DbSet<StudioOrder> StudioOrders { get; set; }
        public virtual DbSet<Team> Teams { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Video> Videos { get; set; }
        public virtual DbSet<Vacation> Vacations { get; set; }
        public virtual DbSet<Like> Likes { get; set; }
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<Mesagge> Mesagges { get; set; }
    }
}
