//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Photo_Video_Studio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vacation
    {
        public int ID { get; set; }
        public Nullable<int> StaffID { get; set; }
        public Nullable<System.DateTime> VacationDateStart { get; set; }
        public Nullable<System.DateTime> VacationDateEnd { get; set; }
    
        public virtual Staff Staff { get; set; }
    }
}
